server:
  port: 8007
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    path: ./data/logs/
    name: ${spring.application.name}